import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export type PageParams = {
  lang: string;
};

export type PageProps = {
  params: PageParams;
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
    children: React.ReactNode,
    params: {lang: string}
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export async function generateStaticParams(): Promise<PageParams[]> {
  return [{ lang: 'en' }, { lang: 'de' }]
}
 